apiVersion: v1
kind: Service
metadata:
  name: {{ template "tile38.fullname" . }}-follower
  labels:
    app: {{ template "tile38.name" . }}
    chart: {{ template "tile38.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: follower
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "tile38.name" . }}
    release: {{ .Release.Name }}
    role: follower
