apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tile38.fullname" . }}-follower
  labels:
    app: {{ template "tile38.name" . }}
    chart: {{ template "tile38.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: follower
data:
  config: |
    {
      "follow_host": "{{ template "tile38.fullname" . }}-leader.{{.Release.Namespace}}.svc.cluster.local",
      "follow_port": {{ .Values.service.port }}
    }